//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopperEntities : DbContext
    {
        public ShopperEntities()
            : base("name=ShopperEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Administrator>()
                .Property(e => e.adAcc)
                .IsUnicode(false);

            modelBuilder.Entity<Administrator>()
                .Property(e => e.adPass)
                .IsUnicode(false);

            modelBuilder.Entity<Comments>()
                .Property(e => e.proID)
                .IsUnicode(false);

            modelBuilder.Entity<Customers>()
                .Property(e => e.cusPhone)
                .IsUnicode(false);

            modelBuilder.Entity<Customers>()
                .Property(e => e.cusEmail)
                .IsUnicode(false);

            modelBuilder.Entity<OrderDetails>()
                .Property(e => e.orderID)
                .IsUnicode(false);

            modelBuilder.Entity<OrderDetails>()
                .Property(e => e.proID)
                .IsUnicode(false);

            modelBuilder.Entity<OrderDetails>()
                .Property(e => e.ordtsThanhTien)
                .IsUnicode(false);

            modelBuilder.Entity<Orders>()
                .Property(e => e.orderID)
                .IsUnicode(false);

            modelBuilder.Entity<Orders>()
                .Property(e => e.cusPhone)
                .IsUnicode(false);

            modelBuilder.Entity<Orders>()
                .Property(e => e.orderDateTime)
                .IsUnicode(false);

            modelBuilder.Entity<Orders>()
                .HasMany(e => e.OrderDetails)
                .WithRequired(e => e.Orders)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<Producers>()
                .Property(e => e.pdcPhone)
                .IsUnicode(false);

            modelBuilder.Entity<Producers>()
                .Property(e => e.pdcEmail)
                .IsUnicode(false);

            modelBuilder.Entity<Products>()
                .Property(e => e.proID)
                .IsUnicode(false);

            modelBuilder.Entity<Products>()
                .Property(e => e.proSize)
                .IsUnicode(false);

            modelBuilder.Entity<Products>()
                .Property(e => e.proPrice)
                .IsUnicode(false);

            modelBuilder.Entity<Products>()
                .Property(e => e.proUpdateDate)
                .IsUnicode(false);

            modelBuilder.Entity<Products>()
                .HasMany(e => e.OrderDetails)
                .WithRequired(e => e.Products)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<Products>()
                .HasOptional(e => e.Rates)
                .WithRequired(e => e.Products);

            modelBuilder.Entity<Rates>()
                .Property(e => e.proID)
                .IsUnicode(false);
        }

        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
    }
}
